language: node_js
node_js:
  - "8"
cache: yarn
services:
  - postgresql
before_script:
  - psql -c "CREATE database ridemyway;" -U postgres
  - psql -c "CREATE USER lupyana WITH PASSWORD 'developer';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ridemyway to lupyana;" -U postgres
  - node /backend/db createAllTables
script:
  - cd backend && yarn install && yarn test
after_success:
  - yarn coveralls
