language: node_js
node_js:
  - "8"
cache: yarn
services:
  - postgresql
before_script:
  - psql -c "create database ridemyway;" -U postgres
  - psql -c "CREATE USER lupyana WITH PASSWORD 'developer';" -U postgres
  - psql "GRANT ALL PRIVILEGES ON DATABASE ridemyway to lupyana;" -U postgres
  - npm run build
script:
  - cd backend && yarn install && yarn coveralls
